### ISSUE TITLE
Flex axes w/negative values/temp rebuild?

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Roboto-Flex#101]
The current version of indesign, (2020), has a bug that disallows it to work properly with axes containing negative values. 

"Seems like InDesign 2020 doesn’t like slnt, YTDE, YTAS figures, and GRAD below 0.", reports David Yun. 

FB have confirmed, the latest version, 2020 shows the axes but when trying to activate them, turns text to missing font color. 

We've also tested and everywhere else works fine , including Illustrator. 

Options are to
remake temp build with all + values, no - values
   Wax can get going right away.
   future compositions will need to use same temp version.
wait for next version of Indesign

**Comment by dberlow** [comment]
Temp build has been made and Wax notified.

**Comment by davelab6** [comment]
Please file a bug with Adobe :)

**Comment by davelab6** [comment]
Was a big filed with Adobe?  Do their bugs have public URLs? 

Since this was back in April, maybe the lastest InDesign prerelease has a fix? 

https://www.adobeprerelease.com/beta/C6DFA254-C40C-4EEB-8F6D-F4AEDA2E6171/feedback/home seems to be the buf reporting URL if not done

**Comment by davelab6** [comment]
@sannorozco do you know if this was fixed in InDesign? If yes, https://github.com/TypeNetwork/Roboto-Flex/pull/124 can be merged

**Comment by sannorozco** [comment]
@davelab6 yes it is.
