### ISSUE TITLE
Cyrillic review - Regular

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Roboto-Flex#106]
Straight issues:
1. Ghestroke, Kabashkircyr, Cheverticalstroke-cy, hard and more? are composite and contour combo
2. De contours, is tripple overlap in lower right right?
3. Structure  of Zhe, Ka, Kaverticalstrokecyr (and moreE?) do not allow compatible inktraps w/Latin.
4. why does Tedescender-cy have overlapping tail, Endescender not.
5. Ucyr was mqded from l.c. y, which had 2 points at start to allow separation of left diagonal and tail. start point (index 0),is now in middle of glyph.
6. why have contours abut in the Ef?
7. what's the advantage of 3 contours in te?

More in discussion,

**Comment by ilyaruderman** [comment]
All issues were addressed in my latest commit from yesterday — please have a look.
All technical issues are fixed (I hope). Kk's were reconsidered to another construction.

**Comment by dberlow** [comment]
I am working in the master branch of this project only.

Changing to other branches is just too dangerous when trying to address this project across the broad spectrum I need to. Switching between the master, Greek and Cyrillic branches, while trying to also commit documentation and other stuff on this project is not going to work.

**So, if you want me to review a file, attach it and send it to me for now**

Thanks.

Santiago, please read. Then, if you can find a temp file of Flex Regular that Glyphs created automatically in the cyrillic branch when the wrong version was opened, please delete it.

**Comment by ilyaruderman** [comment]
I don't mind merging branches together and working with you in the master one. But that shoud be your decision.

**Comment by dberlow** [comment]
for now, if you want a review, copy me the ufo, thanks.
