### ISSUE TITLE
Glyph widths need review

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Roboto-Flex#110]
Latest version shows many composite glyphs not yet properly unitized.

<img width="939" alt="Screen Shot 2020-07-08 at 5 14 32 AM" src="https://user-images.githubusercontent.com/1956494/86901125-2a1a6d80-c0da-11ea-8d51-b55f5b7bd0f7.png">
<img width="979" alt="Screen Shot 2020-07-08 at 5 12 49 AM" src="https://user-images.githubusercontent.com/1956494/86901126-2ab30400-c0da-11ea-8bc6-970c3cd172e8.png">
<img width="986" alt="Screen Shot 2020-07-08 at 5 12 22 AM" src="https://user-images.githubusercontent.com/1956494/86901127-2ab30400-c0da-11ea-9a76-3571e7027ae6.png">

Let me know schedule for corrections, and/or let me know and I will address.

Thanks.

**Comment by sannorozco** [comment]
Hhmm that’s weird, let me check.

**Comment by sannorozco** [comment]
I don’t see the issues you mention, maybe a rendering issue on your end?

<img width="1773" alt="Screen Shot 2020-07-08 at 9 30 11 AM" src="https://user-images.githubusercontent.com/1184152/86934613-85ac2180-c101-11ea-9a45-551e6a12db2a.png">

<img width="1437" alt="Screen Shot 2020-07-08 at 9 31 16 AM" src="https://user-images.githubusercontent.com/1184152/86934633-8a70d580-c101-11ea-9f7c-995583ac7677.png">
