### ISSUE TITLE
Latin k, kgreenlandic, Cyrillic ka and Greek kappa

### ISSUE THREAD

**Issue by irenevl** [TypeNetwork/Roboto-Flex#111]
I'm updating the Greek for Roboto-Flex and discovered this issue of inconsistency of kgreenlandic. In all styles it's a different design from latin k (maybe by choice?) but the main problem is that it's not aligned on the x-height in Regular and wght1000 styles.
I saw that @ilyaruderman has chosen not to follow the Latin design for his ka and I think his design is good for the Greek too.
I'm attaching a PDF with the glyphs in the main styles.

[kgreenlandic.pdf](https://github.com/TypeNetwork/Roboto-Flex/files/5003164/kgreenlandic.pdf)

**Comment by sannorozco** [comment]
Yes, we can use @ilyaruderman’s ka for greek too 🙂
