### ISSUE TITLE
Prep for Classic Greek replacement spin-off

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Roboto-Flex#114]
The picture shows U&l.c. of Flex greek extremes:
1. fix all accent positioning. 
2. get classic extreme 
<img width="2460" alt="Screen Shot 2020-08-12 at 11 29 29 AM" src="https://user-images.githubusercontent.com/1956494/90036314-ded31c00-dc90-11ea-95f5-b6879fc627b7.png">
metric

**Comment by irenevl** [comment]
UC accent position is fixed and the spacing of omega and omega tonos

20200812 Greek WIP commit:

update of accented UC for:
- RobotoFlex-wdth25
- RobotoFlex-Regular
- RobotoFlex-wdth151
- RobotoFlex-wght100
- RobotoFlex-wght1000

update of spacing of omega and omegatonos:
- RobotoFlex-wdth25
- RobotoFlex-Regular
- RobotoFlex-wdth151
- RobotoFlex-wght100
- RobotoFlex-wght1000
