### ISSUE TITLE
.notdef

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Roboto-Flex#130]
This was a rectangle made of 4 rectangles, (twice the needed storage space to make an open rectangle, and a pair of crossing rectangles. 

It contained 6 counters, 3 of which were in the wrong direction. 

The default now has a design for this glyph that has four contours all in the correct direction, and 8 fewer points 

It needs to propagated to all other masters.

**Comment by sannorozco** [comment]
Fixed and updated VF
