### ISSUE TITLE
Rename TTF to include all axes

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/Roboto-Flex#137]
`/fonts/RobotoFlex[slnt,wdth,wght,opsz].ttf` lists the registered axes, but now need to be renamed now that it has more axes. 

Custom axes in all caps first, and then registered axes lowercase, all ordered alphabetically 

For example [Recursive](https://github.com/google/fonts/blob/main/ofl/recursive/) is `Recursive[CASL,CRSV,MONO,slnt,wght].ttf`

**Comment by sannorozco** [comment]
renamed Vf to RobotoFlex[GRAD,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,XOPQ,XTRA,opsz,slnt,wdth,wght].ttf
