### ISSUE TITLE
Location of Ecircumflexgrave

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Roboto-Flex#142]
If certain grave is on the right, Amstelvar is incorrect?
<img width="480" alt="Screen Shot 2021-08-22 at 6 15 25 AM" src="https://user-images.githubusercontent.com/1956494/130351554-79620800-bf6e-4abd-8d04-11317b8016b6.png">

**Comment by sannorozco** [comment]
Yes, I’m correcting it as I go through ;)
