### ISSUE TITLE
Generating static instances

### ISSUE THREAD

**Issue by sannorozco** [TypeNetwork/Roboto-Flex#144]
Script ready for generating instances, just commented full optical sizes and grades ranges for testing only generate opsz14 x GRAD0 combinations of weights & widths.

Proposed folder structure `GRAD0-opsz14-wdth100-SLNT0` for easy readability?

<img width="1160" alt="Screen Shot 2021-09-10 at 7 01 55 PM" src="https://user-images.githubusercontent.com/1184152/132929299-ee8f1637-b426-45bc-b68e-eea2925ffdda.png">

Recommendations? @davelab6 @chrissimpkins @dberlow

Need to add extra steps for modifying name table, and others for fontbakery QA tests.

**Comment by chrissimpkins** [comment]
Folder structure LGTM.  Do you intend to gen the full 3k+ "Many" instance set that David proposed?  How will you approach the name tables?
