### ISSUE TITLE
Font weight range limited in Firefox browser

### ISSUE THREAD

**Issue by barmadrid** [TypeNetwork/Roboto-Flex#145]
When adjusting font weight using Firefox inspect tool, RobotoFlex is only producing 2 weights (regular and medium - based on what I see) within the whole 100-900 weight range.

Please see below.

Font weight **(100 to 500)** - _No change, all Regular_:

![100-500](https://user-images.githubusercontent.com/61072940/133908425-6a7344c4-8e02-42ef-8438-404213b882d6.png)

Font weight **(600 to 900)** - _No change, Medium only_:

![600-900](https://user-images.githubusercontent.com/61072940/133908445-2b4beb4f-d8b6-4b09-9b91-3da33069e173.png)

Is this by design?

For comparison, regular Roboto does change its weight from light to black when I adjust the weight slider within the inspect tool.

Thanks in advance!

**Comment by davelab6** [comment]
What URL are you trying this on?

**Comment by barmadrid** [comment]
> What URL are you trying this on?

https://github.com/TypeNetwork/Roboto-Flex

I also tried it on: https://en.wikipedia.org/wiki/Main_Page
and got same results.

**Comment by davelab6** [comment]
I'm confused. That page made by GitHub doesn't use the fonts in the repo.

**Comment by barmadrid** [comment]
Sorry, I forgot to mention.

First, I have set RobotoFlex as default sans-serif system font (through fontconfig).
Then to double test, I tried on different PC, installing the font and changing both pages font family to RobotoFlex within inspect tool.

**Comment by barmadrid** [comment]
Hi @sannorozco
Do you know if there's any progress on this?
Thanks

**Comment by dberlow** [comment]
I’m not sure what makes this a font and not a browser issue or a markup restriction that applies to a default font. I can say for certain that there is no data in the font that directs any software to skip any weights, widths or other designspace locations in the font, whether the axis is registered or custom.

**Comment by davelab6** [comment]
> I have set RobotoFlex as default sans-serif system font (through fontconfig).

I'm sorry we can't help you with this set-up. I assume this is a problem with fontconfig.
