### ISSUE TITLE
Remove Overlaps in Static Fonts

### ISSUE THREAD

**Issue by AutismIsMySuperpower** [TypeNetwork/Roboto-Flex#147]
Please remove overlaps and static fonts so that way people with Apple computers can use the static fonts. And also add all of the glyphs that are not in the standard fonts but in the variable font and add all of the glyphs that are in the original Roboto.

**Comment by sjad81** [comment]
- [x]

**Comment by dberlow** [comment]
Both overlaps and glyph repertoires are entirely to the specification of the project by Google.

**Comment by davelab6** [comment]
@AutismIsMySuperpower @sjad81 when the font is finalized and available from Google Fonts, please report any issues with the files to github.com/google/fonts or this repo; until then, this project is only offered on an 'as is' basis and hasn't had a 'real' release, the files you see are work in progress
