### ISSUE TITLE
Degree symbol weight min

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/Roboto-Flex#149]
![Frame 26080308](https://user-images.githubusercontent.com/261579/150265219-b35e3a1f-f166-48bc-b9b0-5329aceec1f5.png)

Should be more circular?

**Comment by dberlow** [comment]
Not exactly sure where the Glyph is coming from, as all we have delivered is ascii, 128 glyphs. Degree is a future glyph to complete
.

**Comment by dberlow** [comment]
These 10 duovars and trivars and one main are revised.
opsz 8, wdth 25, wght 400 repaired
opsz 8, wdth 25, wght 100 repaired
opsz 8, wdth 151, wght 400 repaired
opsz 8, wdth 151, wght 100 repaired
opsz 14, wdth 25, wght 400 repaired
((opsz 14, wdth 25, wght 1000)) repaired weight as well
opsz 144 wdth 25 wght 400 repaired
opsz 144 wdth 25 wght 100 repaired
opsz 144, wdth 151, wght 100
opsz 144, wdth 25, wght 1000 repaired
opsz 144, wdth 151, wght 1000 repaired

11 changed files committed. 

Reviewers could be advised of change. 

Could do build or wait for more.

**Comment by sannorozco** [comment]
Fixed and updated VF.
