### ISSUE TITLE
GRAD axis changes the adv width of some glyphs

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/Roboto-Flex#151]
The GRAD axis affects the width of the following glyphs:

```
iebrevecyr
zhebrevecyr
tcaron
ae
Be
zhedieresiscyr
iemacroncyr
aeacute
manat
hryvnia
io
tenge
schwa
yen
zhedieresiscyr
oe
schwacyr
ie
```

**Comment by dberlow** [comment]
Changes committed, thanks. 
Santiago,
Sources effected do not conflict with sources committed for degree sign fix.

**Comment by davelab6** [comment]
Marc, how did you check this?😅

I thought fb had an automated check in place to prevent this? 🤣

**Comment by m4rc1e** [comment]
> Marc, how did you check this?😅
> I thought fb had an automated check in place to prevent this? 🤣

Yep, I used it. Damn nice check tbf.

**Comment by sannorozco** [comment]
Fixed.
