### ISSUE TITLE
Cyrillic/Latin glyph widths problem

### ISSUE THREAD

**Issue by EbenSorkin** [TypeNetwork/Roboto-Flex#156]
Cyrillic glyphs widths don't match Latin in some of the design space. The issue is seen in : Opsz 8, Wght 100-900, Wdth 25 and the issue does not seem to have a Slnt or Grad component.

Of course, components re-used from the Latin do not have this issue.

**Comment by dberlow** [comment]
If you mean the glyphs widths don't match after being borrowed by Cyrillic from Latin — we'll develop a script to check all of them all over the design space. Thanks.

**Comment by EbenSorkin** [comment]
She doesn't. She means that the sense that the glyphs have of
belonging together in width terms holds together well in the borrowed ones
( logical since they are components!) but the others don't. My guess is
that the Latin maybe got a bit more attention than the parts of the
Cyrillic that are (non-borrowed) and the Cyrillic needs to catch up.

**Comment by sannorozco** [comment]
Yes, we’re taking care of this soon, thanks!

**Comment by sannorozco** [comment]
Fixed.
