### ISSUE TITLE
doubled letters - wght: 400 | wdth: 100 | slnt: 0 | GRAD: 0 | opsz: 14

### ISSUE THREAD

**Issue by EbenSorkin** [TypeNetwork/Roboto-Flex#167]
in opsz 14 I see doubled t, j, f, l, i, seem a bit too tight. The word 'Safflower' has the letters ffl too crushed up for example.

**Comment by dberlow** [comment]
4 is off the size scale, mean 14?

**Comment by EbenSorkin** [comment]
Yes - typing too fast. Thanks!

**Comment by dberlow** [comment]
On top of not being at all apparent to me, making changes to the default requires further discussion
<img width="502" alt="Screen Shot 2022-02-10 at 7 28 02 AM" src="https://user-images.githubusercontent.com/1956494/153408742-6cc9b373-1959-40f6-b283-2290d59bbd0c.png">
<img width="502" alt="Screen Shot 2022-02-10 at 7 27 13 AM" src="https://user-images.githubusercontent.com/1956494/153408746-0a4dcdeb-a30e-48e9-bc76-fdf1e8272b85.png">
.

**Comment by davelab6** [comment]
Since we want the 14 to be closer to the legacy Roboto, I don't want to change this, so closing
