### ISSUE TITLE
Ukrainian Ї (Yi) 

### ISSUE THREAD

**Issue by vikagrabowska** [TypeNetwork/Roboto-Flex#176]
Currently Ukrainian lowercase ї (yi) has squeezed dots to avoid the collision in pairs such as її ії ’ї, but uppercase Ї (Yi) doesn't. Since ЇЇ pair also exists and is frequent in Ukrainian (it means "her") I would recommend to make dots squeezed in UC Ї as well. 

[Ukrainian - Yi and yi.pdf](https://github.com/TypeNetwork/Roboto-Flex/files/7994830/Ukrainian.-.Yi.and.yi.pdf)

**Comment by dberlow** [comment]
SO and IR, 
Could you wrap this additional diacritic and composite into the edits coming forward on Cy-extended please.
Let me know, thanks.
