### ISSUE TITLE
latin small letter dotless i (0x0131) is missing

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/Roboto-Flex#181]

**Comment by sannorozco** [comment]
We have it named as idotless.

**Comment by dberlow** [comment]
That was inherited from the upstream masters.

**Comment by m4rc1e** [comment]
> We have it named as idotless, we’ll rename it.

No need to rename it, just give it the unicode 0x0131.

**Comment by sannorozco** [comment]
Done.
