### ISSUE TITLE
Cyrillic widths break in wght: 100-400 | wdth: 25 | slnt: 0 | GRAD: 0 | opsz: 8

### ISSUE THREAD

**Issue by vikagrabowska** [TypeNetwork/Roboto-Flex#202]
Cyrillic widths don't match Latin.
<img width="1755" alt="Screenshot 2022-02-05 at 13 10 54" src="https://user-images.githubusercontent.com/78556166/152641877-cecd0499-8902-48f7-b976-fc8ccca0ed54.png">

**Comment by dberlow** [comment]
The issue is not evident in the sources, please confirm, thanks.
<img width="1132" alt="14,100 400,25 Cy vs La" src="https://user-images.githubusercontent.com/1956494/153198665-6364633f-fa52-4ac2-95dd-25726a7caa45.png">

**Comment by dberlow** [comment]
Okay, thanks.

**Comment by vikagrabowska** [comment]
I looked again at opsz 8 wdth 25.
wght 100 is improved in comparison to the previous version.
But surprisingly in wght 400 the old issues with Cyrillic widths remain. Can you confirm that your screenshots were presenting opsz 8 (and not 14)? Otherwise I'm not sure what is the reason for a difference between your source and most recent .ttf from GitHub. 
<img width="1647" alt="Screenshot 2022-02-09 at 21 11 02" src="https://user-images.githubusercontent.com/78556166/153282645-7e3fec1d-a515-44e9-a036-a8929461342e.png">
