### ISSUE TITLE
¿ - wght: 100/400/900 | wdth: 25/100/151 | slnt: 0 | GRAD: 0 | opsz: 14

### ISSUE THREAD

**Issue by EbenSorkin** [TypeNetwork/Roboto-Flex#212]
* ¿ - This glyph doen't have the reversed spacing of the ? and doesn't sit evenly on two sides of H.  This can be fixed with kerning. And if we want to emphasize non-kerned performance not sucking this is the right choice because it doesn't clash with A! But if we want less kerning overall and assume a kerned performance then this doesn't seem optimal. I don't think the first argument is the one we mean to assert however because so much else about the design doesn't err in this direction. 

_Exception: wght: 400 | wdth: 100 | slnt: 0 | GRAD: 0 | opsz: 14 - this one looks inevitable and right given that the reversed question mark only descends just so low._

**Comment by dberlow** [comment]
SO, I've gone through the mains and corrected 3 styles with questiondown flipped but not re-spaced. 
Can you script to check ?! vs inverted?

**Comment by EbenSorkin** [comment]
Since I saw that an update fixed one of Vika concerns I am going to go grab
the new TTF VF and re- check.

**Comment by EbenSorkin** [comment]
This seems fixed
