### ISSUE TITLE
Set up a typical gf project CI with Github Actions

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/Roboto-Flex#213]
Google Fonts contributors have developed a typical Continuous Integration system to help keep projects in a good state using Github Actions.

As this project enters the end zone to a v1.0 release, I'd like to see this set up on this repo too. 

@sannorozco please set up time with @m4rc1e to learn the latest details

**Comment by m4rc1e** [comment]
Already done. We're using the ufr template, #177
