### ISSUE TITLE
Cyrillic Slants in opsz 14. Wght: 100/400/900 | wdth: 25/100/151 | SLNT: -10 | grad: 0 | opsz: 14

### ISSUE THREAD

**Issue by vikagrabowska** [TypeNetwork/Roboto-Flex#226]
wght: 100/400/900 | wdth: 25/100/151 | SLNT: -10 | grad: 0 | opsz: 14

**wght: 100 | wdth: 100 |** SLNT: -10 | grad: 0 | opsz: 14

Proportions of both Latin and Cyrillic don't match upright (slnt 0), they are much narrower. As proportions in upright and slant in the rest of width and weight range inside opsz 14 are pretty even this looks unusual. Additionally proportions in Cyrillic look inconsistent for groups of letters. I suspect that wght 100 wdth 100 might be in fact wght 100 wdth 25.
____________________________
**wght: 100 | wdth: 25 |** SLNT: -10 | grad: 0 | opsz: 14

The proportions in Cyrillic are uneven, but they seem to be consistent to slnt 0 (I described it [here]. (https://github.com/TypeNetwork/Roboto-Flex/issues/207))
б - tail looks too thin before joining the bowl. 
breve.cyr, breve.cyr.case are shifted 

____________________________
**wght: 400 | wdth: 25 |** SLNT: -10 | grad: 0 | opsz: 14

б - tail looks too thin before joining the bowl 
breve.cyr, breve.cyr.case are shifted 
пн - very narrow and inconsistent with other lettres from the same group
ич - too narrow
иж - too dark
И - is wider than is slnt 0
ы - the distance between two elements is larger than in slnt 0
з - inner curve and outer curve seem to be less harmonised with each other than in other letters.
Я, Ъ, Ь are too narrow compared to P. This seems to be present in slt 0 as well, but is definitely stronger in slnt -10.

**Comment by sannorozco** [comment]
Updating opsz14 wdth25 slnt-1 & opsz14 wdth151 slnt -1.

**Comment by vikagrabowska** [comment]
Thanks for letting me know
