### ISSUE TITLE
Proportions issues in wght: 100 / 400 | wdth: 25 / 100 | slnt: 0 / -10 | GRAD: 0 | opsz: 8

### ISSUE THREAD

**Issue by vikagrabowska** [TypeNetwork/Roboto-Flex#227]
wght: 100 | wdth: 100 | slnt: -10 | GRAD: 0 | opsz: 8
Proportions in SLNT -10 of both Latin and Cyrillic don't match upright (slnt 0), they are much narrower. I already reported similar issue in Opsz 14 | wdth 100 | wght 100.

wght: 400 | wdth: 25 | slnt: 0 / -10 | GRAD: 0 | opsz: 8
Proportions of Cyrillic are uneven. Cyrillic don't match Latin.

**Comment by sannorozco** [comment]
These were and old version, updating letter today.

**Comment by vikagrabowska** [comment]
That's great,  I will look at them after your update and will be checking widths in opsz 144 next instead. Can you also check on Cyrillic **в** in wght: 100 | wdth: 151 | slnt: -10 | GRAD: 0 | opsz: 8? Its drawing is upright instead of being slanted.

**Comment by sannorozco** [comment]
Updated VF.
