### ISSUE TITLE
Cyrillic -э and -С issues in wght: 100 / 900 | wdth: 151 | slnt: 0 / -10 | GRAD: 0 | opsz: 144

### ISSUE THREAD

**Issue by vikagrabowska** [TypeNetwork/Roboto-Flex#228]
wght: 100 | wdth: 151 | slnt: -10 | GRAD: 0 | opsz: 144
э - a bit too much weight on top right part of the curve.
<img width="869" alt="Screenshot 2022-02-11 at 20 56 43" src="https://user-images.githubusercontent.com/78556166/153661851-f38dc732-863b-4afc-8f03-cb3424bbb02c.png">

wght: 900 | wdth: 151 | slnt: 0 / -10 | GRAD: 0 | opsz: 144
Cyrillic С doesn't have the same spacing as Latin C. The right sidebearing is too tight in Cyrillic letter. 

<img width="1208" alt="Screenshot 2022-02-11 at 20 01 54" src="https://user-images.githubusercontent.com/78556166/153661871-906fb5d6-2c01-4aa1-86ef-1383c5be8e6f.png">
<img width="946" alt="Screenshot 2022-02-11 at 20 02 09" src="https://user-images.githubusercontent.com/78556166/153661874-c246c5c4-3fe5-4dab-bd65-96ca25b50fd2.png">

**Comment by sannorozco** [comment]
Updated VF.
