### ISSUE TITLE
Local souce test

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Roboto-Flex#245]
Due to builds report incompatibilities,
  I created a local designspace file for opsz8 in /previews
  skateboard opened and generated a preview style from the sources and this deignspace file.
  the preview is also in /previews

**Comment by m4rc1e** [comment]
Build got broken in b4f39d43433485310581659f5093bae79f1e393e. We shouldn't be merging commits into the main branch if they can't generate. I'll take a look and see what's happened.

**Comment by sannorozco** [comment]
Hey @m4rc1e no need, I’m looking at this and other updates now.

Thanks.

**Comment by m4rc1e** [comment]
Thanks. Also look into #246

**Comment by m4rc1e** [comment]
There's also a single glyph incompatibility which needs solving.

**Comment by sannorozco** [comment]
Fixed.

**Comment by m4rc1e** [comment]
Thanks @sannorozco. Can we focus on the anchor situation tomorrow?
