### ISSUE TITLE
s - 144 opsz | 100 wdth | 900 wght

### ISSUE THREAD

**Issue by EbenSorkin** [TypeNetwork/Roboto-Flex#272]
The lower case s feels a bit less emphatic and like it has less weight and presence than the letters around it in 900 wght. I think if it was permitted to be slightly wider that would give it the little bit of extra weight needed to fix it.

<img width="724" alt="image" src="https://user-images.githubusercontent.com/2181213/156295673-f990b15a-048b-4374-8dad-7952865c4891.png">

**Comment by dberlow** [comment]
added 40 units.
