### ISSUE TITLE
Cyrillic у wght: 100 | wdth: 25 | slnt: 0 | GRAD: -50/0/50 | opsz: 14

### ISSUE THREAD

**Issue by vikagrabowska** [TypeNetwork/Roboto-Flex#275]
у tail is being too dark and getting thicker while approaching the join <img width="1099" alt="image" src="https://user-images.githubusercontent.com/78556166/156418558-98289c7b-3271-44f0-b1ab-b2973ec9f723.png">

**Comment by dberlow** [comment]
Repaired, thanks
