### ISSUE TITLE
Spacing of () {} is inverted on opsz 144 wght 1000 wdth 25 vs 151

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/Roboto-Flex#283]
<img width="1064" alt="Screen Shot 2022-03-02 at 3 11 49 PM" src="https://user-images.githubusercontent.com/261579/156458396-4fe11cfb-e913-4b6a-b977-b430a17bbf38.png">
<img width="1023" alt="Screen Shot 2022-03-02 at 3 11 39 PM" src="https://user-images.githubusercontent.com/261579/156458393-b652cb69-3bf0-45be-937d-6388ea4ffa33.png">

I'm expecting their spacing to be more even, and they are uneven in different ways on both ends of width at 144 wght max

**Comment by sannorozco** [comment]
Fixed.
