### ISSUE TITLE
Hyphens and dashes - 8 opsz | 100/400/900 opsz | 100 wdth 

### ISSUE THREAD

**Issue by EbenSorkin** [TypeNetwork/Roboto-Flex#284]
For a design at 8 opsz I would expect looser spacing of the hyphen and dashes at all weights than I am seeing. The 100 & 900 though seem tighter even than the 400.

These are 100% or 'actual size' renders in a PDF made by drawbot

<img width="274" alt="image" src="https://user-images.githubusercontent.com/2181213/156494278-7eefbf9f-1fc6-4ad4-b509-6cb2ce2b50e6.png">

<img width="265" alt="image" src="https://user-images.githubusercontent.com/2181213/156494298-ca05d9b0-226a-40e2-a4ff-0f7677da1727.png">

<img width="285" alt="image" src="https://user-images.githubusercontent.com/2181213/156494441-5495f902-7fd3-4c3d-a1f2-1d212a88512f.png">

**Comment by dberlow** [comment]
The Dashes are corrected and hyphens loosened
