### ISSUE TITLE
guillemet - 8 opsz - 100 wght - 100 wdth

### ISSUE THREAD

**Issue by EbenSorkin** [TypeNetwork/Roboto-Flex#287]
The light guillemet feel tight vs the other two weights 

<img width="1483" alt="image" src="https://user-images.githubusercontent.com/2181213/156500494-c806c865-3d66-4f39-a375-524edf294846.png">

**Comment by dberlow** [comment]
The singles were shorter, but the spacing was identical in all. 
<img width="201" alt="Screen Shot 2022-03-03 at 3 50 11 PM" src="https://user-images.githubusercontent.com/1956494/156650830-9a89d4b1-0e5e-4dbd-b15e-b150b0945259.png">
