### ISSUE TITLE
Z - 8 opsz | 900 wght | 100 wdth

### ISSUE THREAD

**Issue by EbenSorkin** [TypeNetwork/Roboto-Flex#288]
The cap Z and N feel just a little heavier than the other letters to me

<img width="373" alt="image" src="https://user-images.githubusercontent.com/2181213/156501233-78e4479c-b882-44df-bee2-5ba611df2a84.png">
<img width="280" alt="image" src="https://user-images.githubusercontent.com/2181213/156501398-d12ec947-7f4b-4675-a354-5fe6fa5659f8.png">

**Comment by dberlow** [comment]
repaired
