### ISSUE TITLE
Many currency sumbols have spacing that is too tight - 8/14/144 opsz | all wght | 100 wdth

### ISSUE THREAD

**Issue by EbenSorkin** [TypeNetwork/Roboto-Flex#296]
8
<img width="740" alt="image" src="https://user-images.githubusercontent.com/2181213/157122783-091b46ba-fe49-4948-be09-c10a5d2737d2.png">
<img width="738" alt="image" src="https://user-images.githubusercontent.com/2181213/157122822-81a40865-a3d7-44da-a846-969bc4199ff6.png">
<img width="785" alt="image" src="https://user-images.githubusercontent.com/2181213/157122922-e6e83145-133b-4e5f-ba9a-17708b282a6a.png">

14
<img width="707" alt="image" src="https://user-images.githubusercontent.com/2181213/157123016-901a680b-ee16-4175-93cf-85c19f0ed092.png">
<img width="703" alt="image" src="https://user-images.githubusercontent.com/2181213/157123049-9dd3c43c-667d-4b00-a702-01bbe085429f.png">
<img width="779" alt="image" src="https://user-images.githubusercontent.com/2181213/157123078-ecc06791-a682-4ed9-bf22-5c2a8893748f.png">

144
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/2181213/157123234-4d516d5d-964b-4d52-aabc-1c02ae61afda.png">
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/2181213/157123286-2767bd57-830b-4659-af5e-3c9229a47a7e.png">
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/2181213/157123449-af4efedf-ddec-4106-a866-1a5e982ca33e.png">

Of course, some of these currency symbols are simply not done, but it would be good to get them all spacing consistently.

Will bitcoin keep serifs?

**Comment by dberlow** [comment]
We will check but the sources at 144pt, where glyphs actually exist, all appear correct. 
The proof includes glyphs that are there but not being properly found, or are not in the repertoire. and fallbacks are being used.

**Comment by dberlow** [comment]
Santiago, this confirms that all the monetary symbols work except that there is/are missing  rvrn in the won symbol.

https://user-images.githubusercontent.com/1956494/157135643-ed9b040f-7399-4122-878c-3d667e2e3194.mov

**Comment by EbenSorkin** [comment]
I'll pull the updated file. I took mine that I'm testing at around 4pm
today.

-e.

**Comment by sannorozco** [comment]
Won rvrn is working.
