### ISSUE TITLE
v1.000 release deadline

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/Roboto-Flex#299]
Tomorrow evening 5pm GMT time, I plan to cut the v1.000 release since we've gone way over the deadline. Before I'm able to do this, I expect the sources to have compatible anchors. Can we stop adding new commits an hour before then so I can get this out? we can continue refining once this has been done (I'll let you know when it's safe to continue).

**Comment by davelab6** [comment]
Sounds good Marc.

**Comment by m4rc1e** [comment]
> To confirm, at 4pm gmt tomorrow you want FB to stop committing to the main branch, even locally, like log off the computer style, and then you'll make commits that fix some build process issues and tag a commit as a "prerelease", and then FB can sync those commits, and then continue to commit to main?

Exactly. I should only need an hour to do this.

**Comment by sannorozco** [comment]
Hey Marc @m4rc1e, you can proceed now. Thank you for your help.

Cheers!

**Comment by m4rc1e** [comment]
Cool thank you.

**Comment by m4rc1e** [comment]
Release has been tagged, https://github.com/TypeNetwork/Roboto-Flex/releases/tag/3.001. You folks are now free to pull the changes I've pushed and carry on.

Thank you all for your patience.
