### ISSUE TITLE
Parametric roundup

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Roboto-Flex#66]
docs.google.com/spreadsheets/d/1OS9wOXAB6zeoXy7tf7m8Du4zzMmAQYLCJktehCSZ-T8/edit#gid=0

has all the parameters we're looking for. 

the cells colored gray indicate those that are side bearing points, where in TT they  get index # added after the glyph's points. let me know if that's an issue. 

I'm looking for the values of all the masters in the designspace file:
github.com/TypeNetwork/Roboto-Extremo/blob/master/sources/RobotoExtremo.designspace

if the sheet has the params of the instances  in the same order as the designspace file (?) then I can edit this first sheet and figure out the right order, or if there need to be multiple sheets. 

Let me know. Love to have this by Fri. 
thanks.

**Comment by djrrb** [comment]
Hi @dberlow, I’ve added a “Measurements” sheet to that spreadsheet with the results from the parama-roundup. Hope this is close to what you are looking for.

I’ve modified the roundup script to accommodate hex value input for glyph references as well as truetype phantom points. They’re in a branch now but once I get confirmation that is working I’ll commit that to the parama-roundup master.

**Comment by dberlow** [comment]
This looks great, let me give it a couple of days looking
