### ISSUE TITLE
sketch2slides

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/Roboto-Flex#70]
https://websiddu.github.io/sync-to-slides/

Good stuff, maybe useful when current round of Sketch docs are ready to share with Google design community

**Comment by dberlow** [comment]
That looks great, can’t wait to try!

The Plan doc is posted for your comments: https://github.com/TypeNetwork/Roboto-Extremo/blob/master/docs/Deliverable%20Docs/6.1.1%20Extremo%20Development%20plan.pdf

The deliverables document will be ready this afternoon. There’s a little more writing to do. Then your comment, then release?

The I’ll try converting those to slides once okay.

On Nov 6, 2019, at 1:46 PM, Dave Crossland <notifications@github.com> wrote:

https://websiddu.github.io/sync-to-slides/

Good stuff, maybe useful when current round of Sketch docs are ready to share with Google design community
