### ISSUE TITLE
Pdf proof documents posted

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Roboto-Flex#73]
github.com/TypeNetwork/Roboto-Extremo/tree/master/docs/Sketch%20Docs/11%20x%208.5%20Paginated

Now trying to figure out how Sketch, orders pages, when outputting PDFs.

Does not follow the order of the pages in the page inspector column.
Does not go from top left to bottom right of an array of pages.
Organizing the pages in a single long column, (last resort) must work, but that’s the least practical layout of pages to view or edit in Sketch on screen.

**Comment by sannorozco** [comment]
Updated docs/Sketch Docs/11 x 8.5 Paginated/PROOF PDFs v.1/ExtremoPrintText8-14.pdf with reordered pages.

Sketch export order goes from left to right, top bottom… so what I did is select the first column, then exported as single PDFs, then quickly reordered pages in Preview, thumbnail view on the left.

<img width="1536" alt="Screen Shot 2019-12-11 at 10 17 03 AM" src="https://user-images.githubusercontent.com/1184152/70639012-71518600-1bff-11ea-9ef1-75b0471651bf.png">

**Comment by dberlow** [comment]
"Sketch export order goes from left to right, top bottom… "

That does not explain the output order of either
ExtremoPrintTest48&64pt.pdf or ExtremoPrintTest36pt.

I've made minor edits but no page order changes to those or any other files.

I think, pending your looking at the files above and letting me know, that
we need to do something other than what's been done. ;)

Can I Leave that to you? to print and also deliver printable proofs from
these files?

Let me know.

thanks.

**Comment by sannorozco** [comment]
Yes, I’ll take care of it!
-- 
Santiago Orozco
Typemade

**Comment by dberlow** [comment]
I updated some incorrect labels and quite a few pages all the sketch files are update, and i’ll Update the PDFs in the next few minutes.
