### ISSUE TITLE
Any plans for a slant axis?

### ISSUE THREAD

**Issue by jpamental** [TypeNetwork/Roboto-Flex#74]
Just curious if there are any plans for a slant axis. Currently the 'classic' Roboto variable has width, weight, and slant, but no opsz or GRAD. It would be nice to have one font that includes all of those axes.

**Comment by dberlow** [comment]
We do have plans, thanks for your interest.

I have added a slant master to the next build, ascii only.

It's based on the Default, then:
scaled 97% horizontal,
skewed 10 degrees clockwise, (the axis value will be -10), &
shifted -80.

This matches the previous "italic" regular "H", we'll begin reviewing the
effects on the other glyphs and the design space including that which the
previous family did not slant.

Cheers,

David

**Comment by jpamental** [comment]
Thanks for the update David!

**Comment by dberlow** [comment]
There is a pre-alpha slnt, that currently works best on all styles at smaller sizes. 14 pt down are safe, 144 pt is not, I’ll be looking at what’s going on in between and reporting back soon.

**Comment by jpamental** [comment]
Thanks @dberlow - giving it a whirl and it looks really nice so far. Currently testing it for body copy and figure captions (14-20px or so) and for large blockquotes (largest around 48px) and it's all rendering really nicely.

Question: was it intentional to set the axis as 'SLNT' instead of 'slnt'? (browsers are generally being case-sensitive about axes so it was throwing me a bit until I changed the capitalization)

**Comment by davelab6** [comment]
Roboto's original slant was made with an algorithm custom made by Christian
Robertson, here

https://github.com/google/roboto/tree/master/scripts/lib/fontbuild

**Comment by davelab6** [comment]
SLNT is a undefined custom axis, slnt is defined by the msft registry; it
should not only be lowercase but also comply with the other aspects of the
definition.

**Comment by davelab6** [comment]
To clarify, Classic is scoped as a pure compression upgrade of the previous
static release, so no opsz or grade there. New development is happening
here :)

**Comment by dberlow** [comment]
Sorry I’ll make that an issue should be lowercase SLNT

> On Jan 17, 2020, at 2:32 PM, Jason Pamental <notifications@github.com> wrote:
> 

﻿
Thanks @dberlow - giving it a whirl and it looks really nice so far. Currently testing it for body copy and figure captions (14-20px or so) and for large blockquotes (largest around 48px) and it's all rendering really nicely.

Question: was it intentional to set the axis as 'SLNT' instead of 'slnt'? (browsers are generally being case-sensitive about axes so it was throwing me a bit until I changed the capitalization)

**Comment by jpamental** [comment]
Thanks @dberlow 

(Noting this relates to Issue #75 )

**Comment by davelab6** [comment]
On https://googlefonts.github.io/typography/about-variable-fonts/ the `slnt` styles are now being used, with `font-variation-settings:"opsz" 48, "slnt" -10, "GRAD" 0;`, and it looks like this:

<img width="691" alt="Screen Shot 2020-02-05 at 11 35 07 PM" src="https://user-images.githubusercontent.com/261579/73906237-37ec6e00-4870-11ea-8f00-e3fcf3f170c9.png">

The stroke contrast is a bit wacky =) I know this is early WIP cut of the slnt axis, so I'm wondering what the the timeline is from @dberlow to make the slnt axis styles more palatable for general US English text usage...? :)

**Comment by dberlow** [comment]
This is a cut of the slant axis that is Not part of the deliverables for Jan.

It was done as a courtesy to a designer who wanted to demo it. 
The designer was told it was an early cut, and not to go far from the default.

The designer ignored that simple request. We learned a lesson.

How do you like me to resolve this? 
I can remove the slant axis until it’s on the schedule.
I can stop our current priorities and reprioritize slant.
The composition of the document can use a style closer to the default as recommended.

**Comment by jpamental** [comment]
Nothing was ignored; I assumed that the issue would be addressed as you have time. I've played around with increasing the weight slightly and reducing the amount of slant and it's much less noticeable.

@dberlow I'm keeping an eye on the repo and testing/updating the font file in use whenever there is a new version. Once you and @davelab6 agree on the roadmap, I'd love to know when you'll have time to get the slant axis where you'd like it. 

I don't want to put something in production that nobody is happy with, but would very much like to be able to maintain the blockquote style of large/light/slanted if possible.

**Comment by dberlow** [comment]
Sorry I wasn't clear.

Quoting only the axes that change, the design space location I guess you want to use is around;
opsz48, wght100, slnt -10 ?

Thanks.

**Comment by jpamental** [comment]
Don't worry @dberlow you were very clear in your warning that it wasn't going to work well at larger sizes! It was my decision to design the way I wanted it to end up and wait for the font to catch up.

Ideally we'd be able to use it up to roughly 48px max font-size, with matching opsz, wght 100 and slnt -10

Thank you for anything you can do, and if it's not possible to address in the next couple weeks I'll back off the slant and increase the weight, which will reduce the effect we're seeing with the current use.

Much appreciated!

**Comment by davelab6** [comment]
The slant axis today is good, except for the grade axis:

<img width="634" alt="Screen Shot 2020-04-15 at 8 11 16 AM" src="https://user-images.githubusercontent.com/261579/79335856-ba3c8280-7ef0-11ea-8d59-4cf67d30924b.png">

**Comment by davelab6** [comment]
where it produces reverse contrast

**Comment by dberlow** [comment]
1. As suggested in the notes so far on Slant, parametric axes and grade are not ready. 
All axes with y direction deltas, will need slnt masters for all of the slnt design space. 

This means at least 4 masters per opsz, per axes of the slnt space.

2. Does it make sense to delay the specimen’s composition until all areas of the design space is perfect?


> On Apr 15, 2020, at 8:15 AM, Dave Crossland <notifications@github.com> wrote:
> 

﻿
The slant axis today is good, except for the grade axis, where it produces reverse contrast:
