### ISSUE TITLE
Update Family Name everywhere to 'Roboto Flex'

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Roboto-Flex#95]
Family Name options:
A. Roboto Delta
B. Roboto Extremo
C. Roboto...
   1. ...[wght,wdth,opsz], i.e. registered axes
   2. ...[wght,wdth,opsz,GRAD], I.e. unhidden axes.
   3. ...[all 13 axes here, comma separated]

**Comment by davelab6** [comment]
The Google Fonts and Google Design teams have decided to call this project "Roboto Flex" when it is ready for its first production ready release

**Comment by davelab6** [comment]
- [ ] https://github.com/TypeNetwork/Roboto-Extremo/settings rename the repo to `Roboto-Flex`
- [ ] Update source files, file names, fontinfo metadata
- [ ] Update build scripts and build files
- [ ] Update current sketch/etc documents

**Comment by dberlow** [comment]
This is a great name, thanks!

**Comment by dberlow** [comment]
Santiago,

For speed, and if it makes sense today, what we need to update right away is the output file name and family name, to replace Extremo w/Flex. The rest of the font files and scripts can be updated later. Let me know if this can be done in this build, today, thanks.

**Comment by sannorozco** [comment]
—All sources, docs, VFs are named RobotoFlex
